In [1]:
import pandas as pd

df = pd.read_csv("../data/superstore.csv")

In [2]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [3]:
region_summary = (
    df.groupby("Region")[["Sales", "Profit"]]
    .sum()
    .sort_values(by="Profit", ascending=False)
)

region_summary

               Sales       Profit
Region
West     725457.8245  108418.4489
East     678781.2400   91522.7800
South    391721.9050   46749.4303
Central  501239.8908   39706.3625

The West region generates the highest profit, while the Central region shows comparatively lower profitability despite substantial sales, indicating potential pricing or cost inefficiencies.

In [4]:
category_summary = (
    df.groupby("Category")[["Sales", "Profit"]]
    .sum()
    .sort_values(by="Profit", ascending=False)
)

category_summary

                       Sales       Profit
Category
Technology       836154.0330  145454.9481
Office Supplies  719047.0320  122490.8008
Furniture        741999.7953   18451.2728

In [5]:
subcategory_loss = (
    df.groupby("Sub-Category")["Profit"]
    .sum()
    .sort_values()
)

subcategory_loss.head(10)

Sub-Category
Tables        -17725.4811
Bookcases      -3472.5560
Supplies       -1189.0995
Fasteners        949.5182
Machines        3384.7569
Labels          5546.2540
Art             6527.7870
Envelopes       6964.1767
Furnishings    13059.1436
Appliances     18138.0054
Name: Profit, dtype: float64